-- 이전 table를 삭제
drop table if exists API_ROUTE;

-- 초기 스키마를 정의
create table API_ROUTE
(
    id           bigint generated by default as identity,
    path         varchar(2000) not null,
    method       varchar(20),
    uri          varchar(2000) not null,
    weight_group varchar(50),
    weights      bigint,
    route_id     varchar(50),
    primary key (id)
);

INSERT INTO PUBLIC.API_ROUTE (path, method, uri, weight_group, weights, route_id) VALUES ('/get', 'GET', 'https://httpbin.org/get', 'test', 10, 'nexcore');
INSERT INTO PUBLIC.API_ROUTE (path, method, uri, weight_group, weights, route_id) VALUES ('/service', 'POST', 'http://localhost:8010', 'retail', 10, 'interstellar');


